### ISSUE TITLE
Some isues while testing several guest systems

### ISSUE THREAD

**Issue by vruppert** [Vort/Bochs#4]
Here I have some test results with GeForce setup:

All systems, not critical: BX_ERROR since i/o ports 0x03c3 and 0x03b4 are registered twice.
Win95: icons all black in 16 and 32 bpp modes.
WinXP: system reset during driver installation (versions 93.71 and 91.28 tested).
openSUSE 13.2: switch to 1920x176 resolution, so bit 10 is missing for vertical resultion of 1200.
openSUSE 13.2: with EDID file to avoid issue above: panic sometime later, nothing else happens if I continue.
Knoppix 6.2.1: segfault when driver starts to use the FIFO.

**Comment by Vort** [comment]
> All systems, not critical: BX_ERROR since i/o ports 0x03c3 and 0x03b4 are registered twice.

How can I get access to 2 byte reads without such errors?
`bx_vgacore_c::init_iohandlers` handles only 1 byte reads:
https://github.com/Vort/Bochs/blob/de4494b1bab6a90fa0ef04b973795628f27b71f7/bochs/iodev/display/vgacore.cc#L222-L223
I did not investigated why GeForce needs 2 byte reads however, maybe they happen because of bug.

> Win95: icons all black in 16 and 32 bpp modes.

I noticed this problem, it appears in different varieties depending on Windows and driver version.
Most likely this is several problems in one.

> WinXP: system reset during driver installation (versions 93.71 and 91.28 tested).

What card you tried to install drivers for?
Right now only `geforce3` works with 93.71 driver, `geforcefx5900` and `geforce6800` produce BSOD and instant reboot.
I just figured out that it happens because of wrong handling of multimonitor support, I need to plug unused display ports correctly somehow, don't know how exactly yet.

> openSUSE 13.2: switch to 1920x176 resolution, so bit 10 is missing for vertical resultion of 1200.

This is why I use EDID, right. Probably I should try fixing this bug next.

> openSUSE 13.2: with EDID file to avoid issue above: panic sometime later, nothing else happens if I continue.

What panic?

> Knoppix 6.2.1: segfault when driver starts to use the FIFO.

I know that GeForce emulation fails with fresh versions of Linux, but I did not tested Knoppix yet.
I will probably need to find Linux distros which load relatively fast.
I still remember my 1 hour attempt to boot Linux Mint, such cases almost impossible to debug.

**Comment by vruppert** [comment]
I have now applied some code that should make overriding an i/o mask possible. You only need to move the code with the new mask for ports 0x03c3 and 0x03b4 after init_iohandlers() method.
For the other issues I need to do more tests. The local copy of my fork wasn't up-to-date (missing NBXCFG change), so it may have effects on the test results.

**Comment by vruppert** [comment]
The panic with openSUSE 13.2 no longer appears. It boots to the desktop and uses the AGP aperture. The text in the menus is missing, but I don't know if it is caused by wrong aperture handling or the incomplete GeForce emulation. If the aperture code is okay, I'd like to change the messages to BX_DEBUG.

The segfault with Knoppix still exists. Since this is a live CD you'll see it in a few minutes. These are the last lines of the log:

[knoppix.log](https://github.com/user-attachments/files/19721699/knoppix.log)

**Comment by Vort** [comment]
> If the aperture code is okay, I'd like to change the messages to BX_DEBUG.

I think it's the right thing to do.
I plan to lower logging to debug in my code as well, but first of all, `8-bit read from 0x03da` flood from `vgacore` should be silienced somehow. I plan to create issue about it in Bochs repository.

> The text in the menus is missing, but I don't know if it is caused by wrong aperture handling or the incomplete GeForce emulation

Most likely, incomplete emulation.

> The segfault with Knoppix still exists. Since this is a live CD you'll see it in a few minutes.

I was able to reproduce it.
It happens because of simplified FIFO handling used in my code.
Instead of multidimensional `chs` / `schs` storage I made, data most likely should be stored in plain registers and swapped in and out of context storage area.
It is tricky thing to implement because of scarce documentation.

> You only need to move the code with the new mask for ports 0x03c3 and 0x03b4 after init_iohandlers() method.

I will try to do this tomorrow, thanks.

**Comment by vruppert** [comment]
After your latest changes I thought it would be a good idea to look at the progress of the GeForce emulation.
Windows 95 now shows the icons, but some issues still exist:
- parts of the quick launch area are white
- Explorer tool bar icon background is black
- some other background issues (e.g. desktop background at shutdown dialog)

Original Win98 and Win98SE showing similar behavior

Windows XP now boots to desktop, but there are also background issues.
- welcome message at startup
- start button text and start menu icons

openSUSE 13.2 still has no text in menus and now it hangs when shutting down.

Knoppix 6.2.1 now works normally and the log reports writes to 0x03d0 with len 1 errors.

**Comment by vruppert** [comment]
After the latest change that should fix something in Windows XP, a segfault can happen in the GeForce code. In method vram_read32() an invalid address is used. Before the crash I could see that most of the background issues are still there.

**Comment by Vort** [comment]
Red and purple colors here are because of missing chroma keying, black color is because of missing alpha blending.
![Image](https://github.com/user-attachments/assets/5d7c3426-4402-4398-808f-57eb442475c5)
91434a9 aimed at fixing color keying.

What card you were using when crash happened and what driver version?
Was crash caused by some user activity or it appeared by itself during Windows XP boot?

I know that XP can cause crashes, but during my tests all of them appeared only after interaction with user.

> openSUSE 13.2 still has no text in menus and now it hangs when shutting down.

I did not checked openSUSE yet, but I suspect Linuxes use 3D acceleration to draw text, which means it will require lots of code to make it work.

**Comment by vruppert** [comment]
I can confirm that the mentioned issues in the lower right area of the desktop disappeared. I'm using the geforce3 model and the related VGABIOS. The OS is XP SP3 and the driver version is 93.71. There is no specific action that causes the crash. I could open the start menu and later look for the driver version in the device manager, but before I had the chance to shutdown XP, it crashes when I just move the mouse.
Since the text issue in Linux is more complicated to fix, we should look at the hang at shutdown first. Since the desktop is not usable, I switched to a virtual console, logged in and typed the shutdown command. About two weeks ago some error messages from the nouveau driver appeared on the display and now it hangs at this point.
Your latest change for the rectangle fill command has an effect on Win95. Now the desktop background is black at the network login and shutdown dialog.

**Comment by Vort** [comment]
I suspect that unimplemented clipping feature may cause crashes, but it may be anything else.
I was planning to chase this specific crash, but trying to perform random actions and see what causes problem will be fine too.
It will be probably possible to make problem appear during scrolling of "My Computer" window, however, its rendering looks complex and maybe I will find something simpler.

**Comment by vruppert** [comment]
Since the issue with WinXP looks more complicated, I just had a look at the new Win95 issue caused by the fillrect code. When selecting the shutdown dialog a chessboard pattern should be drawn over the desktop using the pattern color for the 1 bits and the desktop colors for 0. I have only found the setup for the pattern color, but no code for pattern bitmap itself. I guess that's why the desktop around the dialog is completely black.

**Comment by Vort** [comment]
Crash during My Computer scrolling turned out to appear because of negative coordinates passed to `gdi_blit` function. Should be fixed with 2eb08e7.
Complication of this situation comes from the fact that negative coordinates may appear in lots of different places and crash you encountered may have different source.
Some of these bugs can be triggered while moving windows off screen _(I already noticed weird effects with Windows 95)_, but I think it makes sense to implement clipping first.

As for checkerboard pattern, your analysis is most likely correct.
I knew that class `0x44` contained not only colors, some explanations are available [here](https://envytools.readthedocs.io/en/latest/hw/graph/2d/pattern.html).
However, I'm still figuring out what is the best way to develop GeForce emulation:
Right now I think it is better to mix solving of hard problems with solving of easy problems, otherwise discoveries made during solving of hard problems may require rewriting of easy solutions. I'm not that worried about it after I implemented Vista support, but anyway, surprises still can happen.
Also I don't like piling up of copy-pasted code fragments. I expect that implementation of patterns may make this problem worse. I need to think what to do with it.

Regarding hard problems, I have two goals at this moment:
1. Windows XP shows no cursor with `geforcefx5900` / `geforce6800` and 93.71 driver.
2. Windows 7 driver fails with code 43 (it tries to start, but something goes wrong near DDC request step).

Issues with openSUSE shutdown and 0x03d0 errors may appear to be difficult as well.
0x3d0 port is used for RMA (real-mode access) mechanism and reasons why driver may need to access it from protected mode are hard to predict.

**Comment by vruppert** [comment]
After the latest changes Windows XP looks okay 32 bpp mode. I made several tests like I did before and I could normally shutdown XP, since no crash occurs. I don't know whether or not your fix let it disappear, since I still don't know what was the reason for the crash that happened somewhere inbetween.
I remember when I started with the Banshee emulation. I had a usable VGA core and the 3D core that already worked with Voodoo1 and Voodoo2. I had to write all of 2D stuff from scratch. The existing Cirrus stuff helped a little bit and after six months it was almost usable with Win95. Almost 3 years later I have added the last command "Polygon fill" and fixed the last nasty bug visible in Win95. Of course this includes times of low activity. So you may decide how to proceed with GeForce development. I'll have a look how to add a branch for the GeForce development and how to give you the permission to work there.

**Comment by Vort** [comment]
Can you explain what are the benefits of having this branch in the main repository?
Normal way of integration is having this code in main branch of main repository, it will allow users to use and test this code without additional actions of cloning separate repository or separate branch.
But this code is not ready for such integration - it is way behind Cirrus / Voodoo 3 level and I doubt that possibility for users to create thousands of bugreports about something working incorrectly in this code will bring more usefulness than distraction.
It may be useful to have backup of this code in case something happens to my account, but it can be done without additional permissions.

**Comment by vruppert** [comment]
Okay, then let's wait some time before we think about integrating the GeForce emulation in the main Bochs code. Currently my fork of your code could be used as a backup, since I did not have the time to learn how the GeForce works. When we all think it's time to add it to the official Bochs code, it should be called "experimental" and the docs should explain which features are working and mention the incomplete or unimplemented ones. Before a making a new release we also need to decide whether or not it should be enabled for the release binaries.
The Voodoo emulation is present in the main branch right from the start and five months later it has been added to the shortcut scripts when there was a usable Voodoo1 only. Yesterday I noticed that the documentation for the Voodoo devices wasn't updated for a long time. There are still issues, but I decided to remove the "experimental" status.

**Comment by Vort** [comment]
I agree.

I think `Experimental` can be removed from these places as well:
https://github.com/bochs-emu/Bochs/blob/b9c894960755e12134e0ae4ed9dd2d07fdd70dbf/bochs/iodev/display/voodoo.cc#L759-L760
https://github.com/bochs-emu/Bochs/blob/b9c894960755e12134e0ae4ed9dd2d07fdd70dbf/bochs/iodev/display/banshee.cc#L156-L166

**Comment by vruppert** [comment]
I have to talk to Ben Lunt whether or not the experimental status could be removed from the EHCI and xHCI USB controllers, too.

When compiling the GeForce code with gcc there are still a lot of warnings. If you do everything at pixel level, you may never need the IMPLEMENT_BACKWARD_BITBLT stuff. I could add a specific symbol to exclude this section and to get rid of these warnings.

**Comment by Vort** [comment]
With per-pixel approach I don't need pitch and height either.
However, I'm not sure how exactly optimized versions of these algorithms should look like.
I suspect some commands are allowed to work only with VRAM, despite full DMA object being passed.
So maybe per-surface operations are actually possible.
It is better to make algorithms correct first, and then think about optimizations.

**Comment by vruppert** [comment]
There are some more warnings, but we should wait some time until the code is more complete.

I just had a look at my Windows 9x test installations and noticed that some issues disappeared. These are some of the remaining issues. The German version of Win95B and the English version of Win98SE have tooltip issues (both 16 bpp). For a moment they are displayed correctly and then they turn to black. Win95B show a big black symbol in the window you know as "My Computer".

![Image](https://github.com/user-attachments/assets/bdaf3efb-4a76-493e-a3a0-a50fd7112565)

Original Win98 shows tooltips correctly, but some of the symbols are black (32 bpp).

![Image](https://github.com/user-attachments/assets/95a23ea9-44b5-4265-9c4b-3c15bab9db31)

**Comment by Vort** [comment]
> The German version of Win95B and the English version of Win98SE have tooltip issues (both 16 bpp)

Looks like driver tries to render tooltip background with dithering pattern (class `0x44`).

> Win95B show a big black symbol in the window you know as "My Computer".

Do you remember which update allowed My Computer to look like that? Some version of Internet Explorer maybe?
I have Win95B as well, but My Computer here looks simpler:

![Image](https://github.com/user-attachments/assets/4a9ad472-b0ce-4a57-8611-015c0b0159c8)

> Original Win98 shows tooltips correctly, but some of the symbols are black (32 bpp).

I don't have it installed yet and I don't have methods for debugging of icon problems.
Icons are rendered offscreen and cached to disk, so it is better to fix similar problems with more direct rendering path and hope that it will fix icons as well.

**Comment by vruppert** [comment]
I have installed IE 4.0 on Win95 with the desktop extension that also adds the quick launch area beneath the start button (Win98 look and feel). When I switch to 32 bpp mode, this symbol is still black, but the tooltips work correctly then.

**Comment by Vort** [comment]
Looks like test case for class `0x66` _(stretched image from CPU)_, thanks.
Also I see class `0x5d` _(triangle)_ in logs, it should also be responsible for some artifacts.

**Comment by vruppert** [comment]
Today I decided to have a look at the GeForce emulation progress, Some Win98SE symbols still have issues in both 16 and 32 bpp. Since we have an issue with the date/time dialog with Voodoo3 I just had a look what the GeForce shows at the moment.

![Image](https://github.com/user-attachments/assets/02394b0d-85c8-4be1-90ee-948b9f699e2b)

**Comment by Vort** [comment]
> Some Win98SE symbols still have issues in both 16 and 32 bpp.

Please tell:
1. Did you tried to delete `c:\WINDOWS\ShellIconCache` and restart OS? Or to clear icon cache in some other way.
2. What is bit depth of your screenshot?
3. What model of GeForce card is used?
4. What driver version is installed?
5. Did you used commit dbec76431a98a62344de6198a7857182590bccfe?

> Since we have an issue with the date/time dialog with Voodoo3 I just had a look what the GeForce shows at the moment.

There are several classes which I did not implemented yet: `LIN`, `TRI` and `RECT`:
https://envytools.readthedocs.io/en/latest/hw/graph/2d/solid.html

They share many properties and I'm still thinking about deduplication possibility. Also their use is surprisingly rare so I'm not prioritizing them yet.
By the way, linked page has some code for triangle rendering, it may make sense to compare it with implementation for Voodoo 3.

**Comment by vruppert** [comment]
1. Deleting ShellIconCache and restarting OS did not help.
2. The depth of the file is 32 bit, but OS also shows wrong colors in 16 bpp.
3. The GeForce model is FX5900.
4. The last digits of the driver version are 8198.
5. Yes, I have updated sources and rebuilt Bochs at this revision

The incomplete clock in Win95, Win98SE and WinXP, since most of the other stuff looks okay. Fixing the issue above and implementing stretched image for Win95 (we talked about it) are more important.

**Comment by Vort** [comment]
I found one more method of clearing icon cache: [TWEAKUI.ver.1.33.0.0.English.zip](https://github.com/user-attachments/files/20576875/TWEAKUI.ver.1.33.0.0.English.zip), maybe it will help.
This program should be copied to `C:\WINDOWS\SYSTEM` and then launched from control panel:

![Image](https://github.com/user-attachments/assets/a12ae744-656b-417a-858e-aaa10e0187e2)

> and implementing stretched image for Win95 (we talked about it) are more important

I plan to find reproduction method which allows me to control scaling factor. But if I don't find it, then I will try implementing just integer scaling.

**Comment by Vort** [comment]
I decided to implement SIFC class in b785aaa, so large icons of My Computer with desktop extension should be fine now.
However, I feel that this implementation is not robust enough, so if you know about better test cases, with customizable fractional scaling factor, please let me know.

**Comment by vruppert** [comment]
With TWEAKUI I was able to force a rebuild of the icon cache, thanks.
I just tried Win95 with the new image stretching code and I think it's okay for now.
The Voodoo version for stretching support is also relatively simple. When we find better code for this task, we could use it for all devices. I also noticed some progress with 8 bpp support. What do you plan to implement next?

**Comment by Vort** [comment]
> What do you plan to implement next?

I plan to fix ~30 seconds hang, which happens every time DirectX application (2D or 3D) is launched.
This problem may turn out to be hard, but it is kinda blocker, so it needs to go away.
Then I hope to implement at least some of 3D features, intermediate goal is to fix text in various Linuxes.

Regarding other issues you reported:
1. I'm not sure what happens with openSUSE 13.2, but I guess it has problematic version of Gnome, which refuses to work with early GeForce cards for no good reason (`Failed to create texture 2d due to size/format constraints`). Following errors during shutdown may be important, but in case there are low chances of fixing this OS support, chasing this problem is of low priority.
2. I tracked `write to port 0x03d0 with len 1` problem in Knoppix 6.2 to `#define _NV_FENCE() outb(0x3D0, 0);` line in driver. I don't know how memory barriers work, it seems to have no effect on OS operation and RMA mechanism is pretty convoluted and I don't want to touch it without a good reason, so this problem is low priority as well.
3. I did not installed original Win98 yet, but in case problem is still there and not goes away with Tweak UI repair, I plan to look at it in future.

**Comment by vruppert** [comment]
After fixing Win98SE icons with TWEAKUI I was able to do the same with original Win98. The remaining issues in the Windows version I have installed here with Bochs are the incomplete 8 bpp support and the missing clock hands. My installed version of openSUSE 13.2 uses a simple window manager called iceWM. Since text is missing in login dialog and menus, I send the keyboard shortcut ctrl-alt-f1 to switch to console. After typing shutdown command there are some GeForce driver messages printed on the display.

![Image](https://github.com/user-attachments/assets/4a5921b7-d998-4ae2-b5b5-36dd54ed7358)

**Comment by vruppert** [comment]
I just tried to open the DOS prompt in Win98SE and found another issue. The panic "port 0x3d0 access is disabled" occurs, but the DOS prompt works normally after selecting "always continue". I guess writes should be ignored at this point and reads should return 0xff, 0x00 or some other invalid value.

**Comment by Vort** [comment]
> The panic "port 0x3d0 access is disabled" occurs, but the DOS prompt works normally after selecting "always continue".

> Knoppix 6.2.1 now works normally and the log reports writes to 0x03d0 with len 1 errors.

Looks like it's a time to lower logging level for port 0x3d0 access (3000b4399829850f3036fa8f73cf45218f94ce1a).

> ... the incomplete 8 bpp support ...

What problems with 8 bpp support do you notice?

> My installed version of openSUSE 13.2 uses a simple window manager called iceWM.

I installed openSUSE 13.2 with IceWM and can confirm text problems and `sudo poweroff` errors:
<details><summary>Screenshots of openSUSE 13.2 with IceWM</summary>

![Image](https://github.com/user-attachments/assets/b802bbb5-8e0e-42ac-b9f4-ba7c2151c6b5)

![Image](https://github.com/user-attachments/assets/b419a556-b7dd-4faf-a435-314d4251ba88)

</details>

However, I can't confirm `and now it hangs when shutting down`: in my tests, it was shutting down properly, after printing previously mentioned errors.

> I plan to fix ~30 seconds hang, which happens every time DirectX application (2D or 3D) is launched.

This problem was eliminated in 3d7a1e0130517b811cf58055dc270efb0638705b, which now opens possibility for further DirectX-related improvements. For example, it makes sense to fix Jazz Jackrabbit 2 game, which works almost fine, with exception of some textures rendering incorrectly:

![Image](https://github.com/user-attachments/assets/52130a0f-006f-4111-8a79-eb4a293de897)

**Comment by vruppert** [comment]
Thanks, the DOS prompt now works without a panic or other issue.
The hang at shutdown of openSISE 13.2 did occur some weeks ago. At my latest tests it terminates normally with ACPI power off.
I simply tried to run dxdiag after your latest changes for DirectX. I can confirm that it starts up normally. Running the tests doesn't make sense at the moment due to unimplemented features.
The 8 bpp issue with Windows guests is strange. There are still large black areas on the display, but with Bochs snapshot everything looks fine. So I made a screenshot of the active window with Linux.

Bochs snapshot
![Image](https://github.com/user-attachments/assets/c40fa9cd-e601-4c82-992b-5bbc29d20d26)

Linux screenshot
![Image](https://github.com/user-attachments/assets/7beb22c3-9576-4abe-ba1c-bbeebcdd6240)

**Update:** On Linux the blackness appears with SDL2, wxWidgets and X11 guis, but win32 (with wine) is okay. I noticed that the GeForce code never calls the gui method palette_change() to force a screen update if necessary.

**Comment by vruppert** [comment]
After some testing I see some progress with this patch:

```diff --git a/bochs/iodev/display/geforce.cc b/bochs/iodev/display/geforce.cc
index 48eea5dec..e34960385 100644
--- a/bochs/iodev/display/geforce.cc
+++ b/bochs/iodev/display/geforce.cc
@@ -1334,6 +1334,7 @@ void bx_geforce_c::update(void)
   Bit8u * vid_ptr, * vid_ptr2;
   Bit8u * tile_ptr, * tile_ptr2;
   bx_svga_tileinfo_t info;
+  Bit8u dac_size = (BX_GEFORCE_THIS s.dac_shift == 0) ? 8 : 6;
 
   if (bx_gui->graphics_tile_info_common(&info)) {
     if (info.snapshot_mode) {
@@ -1488,9 +1489,9 @@ void bx_geforce_c::update(void)
                       vid_ptr2++;
                     }
                     colour = MAKE_COLOUR(
-                      BX_GEFORCE_THIS s.pel.data[colour].red, 6, info.red_shift, info.red_mask,
-                      BX_GEFORCE_THIS s.pel.data[colour].green, 6, info.green_shift, info.green_mask,
-                      BX_GEFORCE_THIS s.pel.data[colour].blue, 6, info.blue_shift, info.blue_mask);
+                      BX_GEFORCE_THIS s.pel.data[colour].red, dac_size, info.red_shift, info.red_mask,
+                      BX_GEFORCE_THIS s.pel.data[colour].green, dac_size, info.green_shift, info.green_mask,
+                      BX_GEFORCE_THIS s.pel.data[colour].blue, dac_size, info.blue_shift, info.blue_mask);
                     if (info.is_little_endian) {
                       for (i=0; i<info.bpp; i+=8) {
                         *(tile_ptr2++) = colour >> i;
```
The colors are still pale and the hardware cursor colors are still wrong. It simply adds the 8-bit DAC support, but some more work is needed.
The 'win32' gui has no support for the new graphics API, so the gui provides a compatibility layer that also handles the graphics snapshot. In the 8 bpp case the 'is_indexed' section of the update code is used. The new graphics API is supported by the guis I mentioned above. I think you need to try to compile the X gui in a virtual machine or the SDL2 gui on Windows to find a final fix for this issue.

**Comment by vruppert** [comment]
This is the fix for the hardware cursor. Since the colors are correct after reboot, we may need something like the Banshee method set_dac_mode().

```diff --git a/bochs/iodev/display/geforce.cc b/bochs/iodev/display/geforce.cc
index 48eea5dec..30f2cf042 100644
--- a/bochs/iodev/display/geforce.cc
+++ b/bochs/iodev/display/geforce.cc
@@ -1117,7 +1117,14 @@ void bx_geforce_c::draw_hardware_cursor(unsigned xc, unsigned yc, bx_svga_tilein
       for (unsigned cx = cx0; cx < cx1; cx++) {
         Bit8u dr, dg, db;
         if (display_color_bytes == 1) {
-          dr = dg = db = vid_ptr2[0];
+          if (info->is_indexed) {
+            dr = dg = db = vid_ptr2[0];
+          } else {
+            Bit8u index = vid_ptr2[0];
+            dr = (BX_GEFORCE_THIS s.pel.data[index].red << BX_GEFORCE_THIS s.dac_shift);
+            dg = (BX_GEFORCE_THIS s.pel.data[index].green << BX_GEFORCE_THIS s.dac_shift);
+            db = (BX_GEFORCE_THIS s.pel.data[index].blue << BX_GEFORCE_THIS s.dac_shift);
+          }
         } else if (display_color_bytes == 2) {
           EXTRACT_565_TO_888(vid_ptr2[0] << 0 | vid_ptr2[1] << 8, dr, dg, db);
         } else {
```

**Comment by Vort** [comment]
> The new graphics API is supported by the guis I mentioned above.

I saw code fragments in Cirrus/Banshee emulation, which made no difference in my tests with Win32 GUI, so I omitted them.
With descriptions of problems these code paths solve, they can be reintroduced.

> I think you need to try to compile the X gui in a virtual machine ...

This is what I usually do when Linux-specific problem appears.

> ... GeForce code never calls the gui method palette_change() ...

> The colors are still pale ...

> ... we may need something like the Banshee method set_dac_mode().

For me output looks correct with your patches applied (576a4ec24c164590d213d8474d1d1c0f0a677730). I don't know how to reveal additional problems you mentioned:

![Image](https://github.com/user-attachments/assets/c1d8e830-9774-4dcd-8343-6767a987038d)

**Comment by vruppert** [comment]
There is a difference between setting mode with restart and without it. After restart the colors are okay, but when you change mode without restart, e.g. the folder symbol is grey instead of yellow. Tested with Win95 / model 6800GT and Win98SE / FX5900. This is not critical, but we should keep this in mind.

![Image](https://github.com/user-attachments/assets/84d5be36-d627-43a7-9018-3fc8e0cf2212)

![Image](https://github.com/user-attachments/assets/896fffc0-3dc8-4ec6-9e3d-74640a372c5d)

**Comment by Vort** [comment]
> There is a difference between setting mode with restart and without it. After restart the colors are okay, but when you change mode without restart, e.g. the folder symbol is grey instead of yellow.

Nothing wrong happened to folder named "Folder" during my tests:

https://github.com/user-attachments/assets/c771f9c5-e872-4006-87f9-54d108bb0cbc

It seems something else is required for reproduction of this bug.

**Comment by Vort** [comment]
> After restart the colors are okay, but when you change mode without restart, e.g. the folder symbol is grey instead of yellow.

I was able to reproduce this problem with Windows 98 SE and GeForce card.
However, same problem appeared not only with GeForce, but also with Voodoo 3 and even VirtualBox SVGA PCI.
I think it's just a bug in Windows 98.

**Comment by VortNs** [comment]
Because of problems in real life, I may not be able to continue development.
Sorry for offtopic, but I need to notify one more person about it: @orignal, everything related to me is compromised and not safe anymore.
-- Vort

**Comment by sskras** [comment]
Oh dear... @VortNs, I wish you get some personal independence (including an internet service like Starlink), recreate your digital self, and then restart the precious things that you did before. Stay safe and healthy. :)

Anything the internet community could you help with?

**Comment by aqua-rgb** [comment]
Oh man, @VortNs, I wish I don't have any followers (or friends I meant.) sadly... but Stay safe.

Anything like you can create ATI Radeon 8500 on Bochs either? like I can't create ATI Radeon series on Bochs, which means it causes black screen.

Also, I was creating ATI Radeon (likely R200) on Bochs they has Mesa drivers on these...

**Comment by VortNs** [comment]
> ... recreate your digital self ...

Such problems are not as large compared to other ones.

> ... Stay safe and healthy. :) ...

The thing is I got simultaneously two situations  seriously threatening lifes of me and my family.

> Anything the internet community could you help with?

I don't know. My problems are country specific so to speak.

---

It's sad I wasn't able to start implementing rendering of 3D triangles, I was very close to it.
However, I solved most of the hard problems, so if someone decides to continue this work, it will be much easier than creating emulation from scratch.
For example, it is possible to find NeHe OpenGL tutorials, build them with Visual Studio 6 and examine their behaviour in Windows 95.

If someone have questions regarding card operation, I can try answering them, at least for some time.

**Comment by aqua-rgb** [comment]
> It's sad I wasn't able to start implementing rendering of 3D triangles, I was very close to it.

Yeah... I feel so sad for you because you were implementing rendering of 3D triangles, It's so close yet...

> However, I solved most of the hard problems, so if someone decides to continue this work, it will be much easier than creating emulation from scratch.

Yep, but I can create ATI Radeon emulation same as GeForce code on Bochs, I think this is my idea first time.

> If someone have questions regarding card operation ...

But, How about creating a card emulation idea from scratch first time? (like NVIDIA RIVA (even it has NVIDIA RIVA on envytools), or ATI Rage-ATI Radeon)

**Comment by vruppert** [comment]
I'm currently in vacation, but when I return, I intend to create a PR based on Vort's GeForce branch to make it possible to continue the development.

**Comment by sskras** [comment]
@aqua-rgb commented [2 days ago](https://github.com/Vort/Bochs/issues/4#issuecomment-3016691711):

> How about creating a card emulation idea from scratch first time? (like NVIDIA RIVA (even it has NVIDIA RIVA on envytools),

You could probably ping @starfrost013 regarding that, who seems to be implementing NV3 (Riva 128) [and possibly NV4 (Riva TNT) in future] for the different emulator called: https://github.com/86Box/86Box/compare/master...starfrost013:86Box:master

Starfrost even maintains the Wiki dedicated to this effort: https://nvwiki.org/index.php/Main_Page

**Comment by vruppert** [comment]
Closing this issue since the development continues in the main Bochs repository.

**Comment by starfrost013** [comment]
@sskras I'm considering moving my efforts to nv4 because the nv4 is much better documented than the nv3 and is generally much more pleasant to work with (the jank is unreal) - although I absolutely will finish the riva 128 eventually

**Comment by sskras** [comment]
To finish the offtopic:

@starfrost013, re your new efforts: are you going to update your [NV4](https://nvwiki.org/index.php/NV4) documentation just the way you did with [NV3](https://nvwiki.org/index.php/NV3) ?

**Comment by starfrost013** [comment]
Yes
